### PR TITLE
Small fix on infraero.get() class. Now requires year input.

### PR DESCRIPTION
**Pull request by Wangbarros**

### CODE REVIEW

**Comment by Wangbarros** [comment]
Found a way to fix de install package issues I was having. I'll begin working on a new parser for all submodules, in the format:

infraero.get(begin_date='01-2015', end_date='12-2016')
# if no end_date is given, gets from begin_date up to today

As discussed on #8

**Comment by odanoburu** [comment]
hey @Wangbarros, thanks for the PR!

can you research some existing library that already does this kind of parsing? if there isn't, we should discuss how we'll implement that, because we'll need it all over the package! (for instance, I'll need a daily one for the cgu submodule)

**Comment by Wangbarros** [comment]
datetime and dateutil are very useful.

for example (the function I'm writing right now):

def _get_dates_between(begin_date='01-2015', end_date='12-2016'):
    begin = datetime.datetime.strptime(begin_date, "%m-%Y").date()
    end = datetime.datetime.strptime(end_date, "%m-%Y").date()
    between = list(rrule.rrule(rrule.MONTHLY, dtstart=begin, until=end))
    
    return between

Returns all months and years between both dates:

[datetime.datetime(2015, 2, 1, 0, 0), datetime.datetime(2015, 3, 1, 0, 0), datetime.datetime(2015, 4, 1, 0, 0), datetime.datetime(2015, 5, 1, 0, 0), datetime.datetime(2015, 6, 1, 0, 0), datetime.datetime(2015, 7, 1, 0, 0), datetime.datetime(2015, 8, 1, 0, 0), datetime.datetime(2015, 9, 1, 0, 0), datetime.datetime(2015, 10, 1, 0, 0), datetime.datetime(2015, 11, 1, 0, 0), datetime.datetime(2015, 12, 1, 0, 0), datetime.datetime(2016, 1, 1, 0, 0), datetime.datetime(2016, 2, 1, 0, 0)]

It is possible to return all days, hours or even seconds too, if I'm not mistaken.

**Comment by odanoburu** [comment]
that's great, @Wangbarros ! can we just try using a solution that doesn't require dateutil, so that we don't use yet another dependency if we don't have to? there's [this](http://stackoverflow.com/questions/1060279/iterating-through-a-range-of-dates-in-python) and also panda's [data_range](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.date\_range.html).

**Comment by odanoburu** [comment]
@Wangbarros , check my PR #22 ! among other stuff, in bradata.utils you'll find the parser . it's mostly a draft, but should work.

**Comment by odanoburu** [comment]
hey @Wangbarros,  any updates?

**Pull request closed without merging**
