### PR TITLE
Added a function for downloading xls files from Infraero website

### PR DESCRIPTION
**Pull request by Wangbarros**

### CODE REVIEW

**Comment by JoaoCarabetta** [comment]
I added the structure for you to put the code. Go to bradata/infraero/statistics Try to open the __init__ files and understand what is happening. It would be a good idea to make a tutorial with what you understood.

I check and it is working, so try

`python3 setup.py install`
 
and in a python console
```
import bradata
infraero = bradata.Infraero()
infraero.statistics.example()
```
and you should receive a 'oi' as answer.

----

I committed without going through a pull request. I thought that I had a fork in my local. It wont happen again.

**Comment by Wangbarros** [comment]
Added the method to the correct place.

**Comment by JoaoCarabetta** [comment]
I think you should put get_links on the utils.py. It seems a quite useful method

**Comment by Wangbarros** [comment]
Fixed conflicts

@JoaoCarabetta @odanoburu

**Pull request merged**
